//! Dolphin per-game configuration.
//!
//! Dolphin reads `<User>/GameSettings/<GameID>.ini` for per-title overrides.
//! Writing there means the user's global `Dolphin.ini` and `GFX.ini` are never
//! touched -- the settings also apply when they launch Dolphin directly, and
//! nothing has to be restored after a crash.
//!
//! Only keys the user has actually set are written. An absent key means
//! "inherit the global default", which is different from writing the default
//! value explicitly: the latter would freeze the game's settings against future
//! changes to the user's globals.

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

/// Per-game overrides. Every field optional: `None` = inherit global.
#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "camelCase", default)]
pub struct DolphinGameConfig {
    /// "OGL", "Vulkan", "D3D", "D3D12", "Software", "Null".
    pub graphics_backend: Option<String>,
    /// Internal resolution multiplier. 1 = native, 0 = auto (window size).
    pub internal_resolution: Option<u32>,
    /// Anti-aliasing sample count.
    pub msaa: Option<u32>,
    pub anisotropic_filtering: Option<u32>,
    pub vsync: Option<bool>,
    pub widescreen_hack: Option<bool>,
    /// Dual-core is a stability tradeoff; some titles need it off.
    pub dual_core: Option<bool>,
    pub emulation_speed: Option<f32>,
    pub progressive_scan: Option<bool>,
}

impl DolphinGameConfig {
    pub fn is_empty(&self) -> bool {
        *self == Self::default()
    }

    /// Group settings into the INI sections Dolphin expects.
    fn sections(&self) -> BTreeMap<&'static str, Vec<(&'static str, String)>> {
        let mut out: BTreeMap<&'static str, Vec<(&'static str, String)>> = BTreeMap::new();

        let mut core: Vec<(&'static str, String)> = Vec::new();
        if let Some(v) = self.dual_core {
            core.push(("CPUThread", bool_str(v)));
        }
        if let Some(v) = self.emulation_speed {
            core.push(("EmulationSpeed", v.to_string()));
        }
        if let Some(v) = self.progressive_scan {
            core.push(("ProgressiveScan", bool_str(v)));
        }
        if !core.is_empty() {
            out.insert("Core", core);
        }

        let mut video: Vec<(&'static str, String)> = Vec::new();
        if let Some(v) = &self.graphics_backend {
            video.push(("Backend", v.clone()));
        }
        if !video.is_empty() {
            out.insert("Video_Hardware", video);
        }

        let mut settings: Vec<(&'static str, String)> = Vec::new();
        if let Some(v) = self.vsync {
            settings.push(("VSync", bool_str(v)));
        }
        if let Some(v) = self.msaa {
            settings.push(("MSAA", v.to_string()));
        }
        if !settings.is_empty() {
            out.insert("Video_Settings", settings);
        }

        let mut enhancements: Vec<(&'static str, String)> = Vec::new();
        if let Some(v) = self.internal_resolution {
            enhancements.push(("InternalResolution", v.to_string()));
        }
        if let Some(v) = self.anisotropic_filtering {
            enhancements.push(("MaxAnisotropy", v.to_string()));
        }
        if let Some(v) = self.widescreen_hack {
            enhancements.push(("WidescreenHack", bool_str(v)));
        }
        if !enhancements.is_empty() {
            out.insert("Video_Enhancements", enhancements);
        }

        out
    }

    /// Render the INI. Returns `None` when nothing is overridden, so the caller
    /// deletes the file instead of leaving an empty one behind.
    pub fn to_ini(&self) -> Option<String> {
        let sections = self.sections();
        if sections.is_empty() {
            return None;
        }
        let mut s = String::from(
            "# Generated by Selene. Per-game overrides only.\n\
             # Settings absent here are inherited from your global Dolphin config.\n",
        );
        for (section, entries) in sections {
            s.push_str(&format!("[{section}]\n"));
            for (k, v) in entries {
                s.push_str(&format!("{k} = {v}\n"));
            }
        }
        Some(s)
    }
}

/// Dolphin writes `True`/`False` capitalised in its INIs.
fn bool_str(v: bool) -> String {
    if v { "True".into() } else { "False".into() }
}

/// Dolphin's user directory. Portable installs keep a `User` folder beside the
/// executable; otherwise it lives in the platform's roaming data directory.
pub fn user_dir(dolphin_exe: &Path) -> Option<PathBuf> {
    if let Some(dir) = dolphin_exe.parent() {
        let portable = dir.join("portable.txt");
        let local_user = dir.join("User");
        if portable.exists() || local_user.is_dir() {
            return Some(local_user);
        }
    }
    #[cfg(windows)]
    {
        std::env::var("APPDATA")
            .ok()
            .map(|a| PathBuf::from(a).join("Dolphin Emulator"))
    }
    #[cfg(not(windows))]
    {
        std::env::var("HOME")
            .ok()
            .map(|h| PathBuf::from(h).join(".config/dolphin-emu"))
    }
}

pub fn game_settings_path(user_dir: &Path, game_id: &str) -> PathBuf {
    user_dir.join("GameSettings").join(format!("{game_id}.ini"))
}

/// Write (or remove) the per-game INI for `game_id`.
pub fn apply(user_dir: &Path, game_id: &str, config: &DolphinGameConfig) -> Result<()> {
    let path = game_settings_path(user_dir, game_id);
    match config.to_ini() {
        Some(ini) => {
            if let Some(parent) = path.parent() {
                std::fs::create_dir_all(parent)
                    .with_context(|| format!("creating {}", parent.display()))?;
            }
            std::fs::write(&path, ini).with_context(|| format!("writing {}", path.display()))?;
        }
        None => {
            // No overrides left: remove the file so Dolphin falls back cleanly.
            if path.exists() {
                std::fs::remove_file(&path)
                    .with_context(|| format!("removing {}", path.display()))?;
            }
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn empty_config_produces_no_file() {
        assert!(DolphinGameConfig::default().to_ini().is_none());
        assert!(DolphinGameConfig::default().is_empty());
    }

    #[test]
    fn writes_only_the_keys_that_were_set() {
        let cfg = DolphinGameConfig {
            internal_resolution: Some(3),
            ..Default::default()
        };
        let ini = cfg.to_ini().expect("should render");
        assert!(ini.contains("[Video_Enhancements]"));
        assert!(ini.contains("InternalResolution = 3"));
        // Nothing else may appear -- an unset key must stay inherited.
        assert!(!ini.contains("Backend"));
        assert!(!ini.contains("[Core]"));
        assert!(!ini.contains("VSync"));
    }

    #[test]
    fn groups_keys_into_dolphins_sections() {
        let cfg = DolphinGameConfig {
            graphics_backend: Some("Vulkan".into()),
            internal_resolution: Some(2),
            dual_core: Some(false),
            vsync: Some(true),
            ..Default::default()
        };
        let ini = cfg.to_ini().unwrap();
        assert!(ini.contains("[Video_Hardware]\nBackend = Vulkan"));
        assert!(ini.contains("[Core]\nCPUThread = False"));
        assert!(ini.contains("[Video_Settings]\nVSync = True"));
        assert!(ini.contains("[Video_Enhancements]\nInternalResolution = 2"));
    }

    #[test]
    fn uses_dolphins_capitalised_booleans() {
        let cfg = DolphinGameConfig { vsync: Some(true), ..Default::default() };
        assert!(cfg.to_ini().unwrap().contains("VSync = True"));
        let cfg = DolphinGameConfig { vsync: Some(false), ..Default::default() };
        assert!(cfg.to_ini().unwrap().contains("VSync = False"));
    }

    #[test]
    fn apply_writes_then_removes_the_file() {
        let dir = std::env::temp_dir().join(format!("dolphin-cfg-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);

        let cfg = DolphinGameConfig { msaa: Some(4), ..Default::default() };
        apply(&dir, "RMGP01", &cfg).unwrap();
        let path = game_settings_path(&dir, "RMGP01");
        assert!(path.exists(), "INI should have been written");
        assert!(std::fs::read_to_string(&path).unwrap().contains("MSAA = 4"));

        // Clearing every override deletes the file rather than leaving a stub.
        apply(&dir, "RMGP01", &DolphinGameConfig::default()).unwrap();
        assert!(!path.exists(), "empty config should remove the INI");

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn game_settings_path_matches_dolphins_layout() {
        let p = game_settings_path(Path::new(r"C:\Users\x\AppData\Roaming\Dolphin Emulator"), "G8ME01");
        assert!(p.ends_with(r"GameSettings\G8ME01.ini") || p.ends_with("GameSettings/G8ME01.ini"));
    }
}
