/* Phase 0 fixture data.
   These are real entries from d:\Games, including their real title IDs and
   filename quirks, so the shell is exercised against the data it will actually
   meet in Phase 1 rather than tidy invented strings.

   Replaced by the Rust scanner in Phase 1. */

import type { Game } from "./types";

const iso = (d: string) => new Date(d).toISOString();

export const MOCK_GAMES: Game[] = [
  {
    id: "g1",
    title: "Super Mario Odyssey",
    platform: "switch",
    runner: "eden",
    path: "d:\\Games\\Switch\\games\\Super Mario Odyssey [0100000000010000][v0].nsp",
    titleId: "0100000000010000",
    playtimeSeconds: 41 * 3600 + 12 * 60,
    lastPlayedAt: iso("2026-07-16T20:11:00"),
    addedAt: iso("2026-01-04T10:00:00"),
    tags: ["Platformer"],
    favorite: true,
  },
  {
    id: "g2",
    title: "Animal Crossing: New Horizons",
    platform: "switch",
    runner: "eden",
    path: "d:\\Games\\Switch\\games\\Animal Crossing New Horizons [World] [En,Ja,Fr,De,Es,It,Nl,Pt,Ru] [01006F8002326000].nsp",
    titleId: "01006F8002326000",
    playtimeSeconds: 128 * 3600,
    lastPlayedAt: iso("2026-07-18T09:40:00"),
    addedAt: iso("2026-01-04T10:00:00"),
    tags: ["Life Sim"],
    favorite: true,
  },
  {
    id: "g3",
    title: "Pikmin 4",
    platform: "switch",
    runner: "eden",
    path: "d:\\Games\\Switch\\games\\Pikmin 4 [0100B7C00933A000][v0].nsp",
    titleId: "0100B7C00933A000",
    playtimeSeconds: 6 * 3600 + 30 * 60,
    addedAt: iso("2026-02-11T10:00:00"),
    tags: ["Strategy"],
    favorite: false,
  },
  {
    // .nsz -- compressed NSP. Not in the original spec's format list; found on
    // disk and supported natively by Eden.
    id: "g4",
    title: "Deltarune",
    platform: "switch",
    runner: "eden",
    path: "d:\\Games\\Switch\\games\\Deltarune [0100A0D022A68000][v0] (0.62 GB).nsz",
    titleId: "0100A0D022A68000",
    playtimeSeconds: 3 * 3600 + 5 * 60,
    addedAt: iso("2026-06-02T10:00:00"),
    tags: ["RPG"],
    favorite: false,
  },
  {
    id: "g5",
    title: "Super Mario Galaxy",
    platform: "wii",
    runner: "dolphin",
    path: "d:\\Games\\Wii & Gamecube\\Wii Roms\\Super Mario Galaxy.iso",
    // Read from the disc header, not guessed: this is a PAL disc (RMG*P*01).
    // The filename gives no region hint at all.
    titleId: "RMGP01",
    playtimeSeconds: 22 * 3600 + 45 * 60,
    lastPlayedAt: iso("2026-07-12T19:02:00"),
    addedAt: iso("2026-03-19T10:00:00"),
    tags: ["Platformer"],
    favorite: true,
  },
  {
    id: "g6",
    title: "Super Mario Galaxy 2",
    platform: "wii",
    runner: "dolphin",
    path: "d:\\Games\\Wii & Gamecube\\Wii Roms\\[Nintendo Wii] Super Mario Galaxy 2 [NTSC].wbfs",
    // .wbfs wraps the disc, so this came from the header at offset 0x200.
    titleId: "SB4E01",
    playtimeSeconds: 9 * 3600,
    addedAt: iso("2026-03-19T10:00:00"),
    tags: ["Platformer"],
    favorite: false,
  },
  {
    // GameCube, in the same Dolphin library as the Wii titles. Platform comes
    // from the disc magic, not the folder name.
    id: "g14",
    title: "Paper Mario: The Thousand-Year Door",
    platform: "gamecube",
    runner: "dolphin",
    path: "d:\\Games\\Wii & Gamecube\\Gamecube Roms\\Paper Mario - The Thousand-Year Door (USA).iso",
    titleId: "G8ME01",
    playtimeSeconds: 0,
    addedAt: iso("2026-07-20T10:00:00"),
    tags: ["RPG"],
    favorite: false,
  },
  {
    id: "g7",
    title: "Splatoon",
    platform: "wiiu",
    runner: "cemu",
    path: "d:\\Games\\Wii U\\Roms\\Splatoon [AGMP01]",
    titleId: "AGMP01",
    playtimeSeconds: 57 * 3600 + 20 * 60,
    lastPlayedAt: iso("2026-07-17T21:30:00"),
    addedAt: iso("2026-01-20T10:00:00"),
    tags: ["Shooter", "Online"],
    favorite: true,
  },
  {
    id: "g8",
    title: "Skylanders: SuperChargers",
    platform: "wiiu",
    runner: "cemu",
    path: "d:\\Games\\Wii U\\Roms\\Skylanders SuperChargers (USA) (v96).wua",
    playtimeSeconds: 14 * 3600,
    addedAt: iso("2026-01-20T10:00:00"),
    tags: ["Skylanders"],
    favorite: false,
  },
  {
    id: "g9",
    title: "Skylanders: Trap Team",
    platform: "wiiu",
    runner: "cemu",
    path: "d:\\Games\\Wii U\\Roms\\Skylanders Trap Team (USA) (v16).wua",
    playtimeSeconds: 11 * 3600 + 15 * 60,
    addedAt: iso("2026-01-20T10:00:00"),
    tags: ["Skylanders"],
    favorite: false,
  },
  {
    id: "g10",
    title: "Skylanders: Imaginators",
    platform: "wiiu",
    runner: "cemu",
    path: "d:\\Games\\Wii U\\Roms\\Skylanders Imaginators (USA) (v16).wua",
    playtimeSeconds: 0,
    addedAt: iso("2026-01-20T10:00:00"),
    tags: ["Skylanders"],
    favorite: false,
  },
  {
    // Nested wrapper folders + a steam_api.dll -> a Goldberg candidate.
    id: "g11",
    title: "Adventure Time: Explore the Dungeon Because I DON'T KNOW!",
    platform: "pc",
    runner: "native-pc",
    path: "d:\\Games\\Pc\\Adventure Time Explore the Dungeon Because I DON’T KNOW\\Adventure Time Explore the Dungeon Because I DON’T KNOW\\executable\\AdventureTime.exe",
    playtimeSeconds: 1 * 3600 + 40 * 60,
    addedAt: iso("2026-05-08T10:00:00"),
    tags: ["Co-op", "Steam API"],
    favorite: false,
  },
  {
    id: "g12",
    title: "Job Simulator",
    platform: "pc",
    runner: "native-pc",
    path: "d:\\Games\\Vr\\Job-Simulator-SteamRIP.com\\Job Simulator\\JobSimulator.exe",
    playtimeSeconds: 4 * 3600 + 22 * 60,
    lastPlayedAt: iso("2026-07-05T18:00:00"),
    addedAt: iso("2026-05-08T10:00:00"),
    tags: ["VR", "Steam API"],
    favorite: false,
  },
  {
    id: "g13",
    title: "Vacation Simulator",
    platform: "pc",
    runner: "native-pc",
    path: "d:\\Games\\Vr\\Vacation-Simulator-SteamRIP.com\\Vacation Simulator\\Vacation Simulator.exe",
    playtimeSeconds: 2 * 3600 + 10 * 60,
    addedAt: iso("2026-05-08T10:00:00"),
    tags: ["VR", "Steam API"],
    favorite: false,
  },
];
